class DesignValuesModel {
  double screenWidth;
  double screenHeight;
  double topAppBarHeight;
  double bodyHeight;
  double bottomAppBarHeight;
  double horizontalPadding;
  double verticalPadding;
  double curveRadius;
  double buttonCornerRadius;
  double buttonHeight;
  double buttonWidth;
  double containerCornerRadius21;
  double crossAxisSpacing31;
  double mainAxisSpacing13;
  double sectionSpacing89;
  double textContentPaddingHorizontal;
  double textContentPaddingVertical;
  double textCornerRadius;
  double menuButtonHeight;
  double menuButtonWidth;
  double cornerRadius34;
  double roundButtonHeight;
  double roundButtonRadius;
  double roundButtonHorizontalPadding;
  double cornerRadius13;
  double unitDropDownLeftPadding;
  double cornerRadius8;
  double padding13;
  double padding21;
  double boxHeightConstrain;
  DesignValuesModel({
    required this.screenWidth,
    required this.screenHeight,
    required this.topAppBarHeight,
    required this.bodyHeight,
    required this.bottomAppBarHeight,
    required this.horizontalPadding,
    required this.verticalPadding,
    required this.curveRadius,
    required this.buttonCornerRadius,
    required this.buttonHeight,
    required this.buttonWidth,
    required this.containerCornerRadius21,
    required this.crossAxisSpacing31,
    required this.mainAxisSpacing13,
    required this.sectionSpacing89,
    required this.textContentPaddingHorizontal,
    required this.textContentPaddingVertical,
    required this.textCornerRadius,
    required this.menuButtonHeight,
    required this.menuButtonWidth,
    required this.cornerRadius34,
    required this.roundButtonHeight,
    required this.roundButtonRadius,
    required this.roundButtonHorizontalPadding,
    required this.cornerRadius13,
    required this.unitDropDownLeftPadding,
    required this.cornerRadius8,
    required this.padding13,
    required this.padding21,
    required this.boxHeightConstrain,
  });
}
